<a href="https://colab.research.google.com/github/cchz3wei/python-certificate-generator/blob/main/20_Certificate_Generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Goal of this project
# Do analysis
  # missing value
  # format the date or text
# enhance python concepts
# explore 3rd party libraries - reportLab

# pip is python package downloader
!pip install reportlab

Collecting reportlab
  Downloading reportlab-4.4.10-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.4)
Downloading reportlab-4.4.10-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 16.7 MB/s eta 0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-4.4.10

In [2]:
import numpy as np
import pandas as pd

from reportlab.lib.pagesizes import landscape, A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

In [3]:
df = pd.read_excel("/content/drive/MyDrive/dataset.xlsx")
df

                  Name                 Course   CourseLevel       Date
0   Christy Cunningham                 Python      Beginner 2023-09-10
1       Douglas Tucker                 PYTHON       MASTER  2023-09-11
2       Travis Walters                   Java  Intermediate 2023-09-12
3     Nathaniel Harris        Web Development      Advanced 2023-09-13
4                    -                    NaN      Advanced        NaT
5         Tonya Carter  AI & Machine Learning      Beginner 2023-09-14
6           Erik Smith     Mobile Development      Beginner 2023-09-15
7   Kristopher Johnson                 Python      Beginner 2023-09-16
8      Jonathan Bucker                    NaN           NaN        NaT
9          Robert Buck                 PYTHON       Master  2023-09-17
10     Joseph Mcdonald                   Java  Intermediate 2023-09-18
11       Jerome Abbott        Web Development      Advanced 2023-09-19
12       William Riley  AI & Machine Learning      Beginner 2023-09-20

In [4]:
df = df.dropna()

In [5]:
df['Date']

# format date, use dt in Pandas
# in Pandas we df --> Dataframe & dt --> datetime
# dateimte --> strftime
# %Y --> 2023 compare to %y ---> 23

df['FormattedDate'] = df['Date'].dt.strftime("%d/%m/%Y")

/tmp/ipykernel_238/1003050912.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FormattedDate'] = df['Date'].dt.strftime("%d/%m/%Y")

In [6]:
df['FormattedDate'].dtype

# 0 - Object --> string

dtype('O')

In [7]:
df

,Name,Course,CourseLevel,Date,FormattedDate
0,Christy Cunningham,Python,Beginner,2023-09-10,10/09/2023
1,Douglas Tucker,PYTHON,MASTER,2023-09-11,11/09/2023
2,Travis Walters,Java,Intermediate,2023-09-12,12/09/2023
3,Nathaniel Harris,Web Development,Advanced,2023-09-13,13/09/2023
5,Tonya Carter,AI & Machine Learning,Beginner,2023-09-14,14/09/2023
6,Erik Smith,Mobile Development,Beginner,2023-09-15,15/09/2023
7,Kristopher Johnson,Python,Beginner,2023-09-16,16/09/2023
9,Robert Buck,PYTHON,Master,2023-09-17,17/09/2023
10,Joseph Mcdonald,Java,Intermediate,2023-09-18,18/09/2023
11,Jerome Abbott,Web Development,Advanced,2023-09-19,19/09/2023
12,William Riley,AI & Machine Learning,Beginner,2023-09-20,20/09/2023

In [8]:
df = df.drop('Date', axis=1)
df

                  Name                 Course   CourseLevel FormattedDate
0   Christy Cunningham                 Python      Beginner    10/09/2023
1       Douglas Tucker                 PYTHON       MASTER     11/09/2023
2       Travis Walters                   Java  Intermediate    12/09/2023
3     Nathaniel Harris        Web Development      Advanced    13/09/2023
5         Tonya Carter  AI & Machine Learning      Beginner    14/09/2023
6           Erik Smith     Mobile Development      Beginner    15/09/2023
7   Kristopher Johnson                 Python      Beginner    16/09/2023
9          Robert Buck                 PYTHON       Master     17/09/2023
10     Joseph Mcdonald                   Java  Intermediate    18/09/2023
11       Jerome Abbott        Web Development      Advanced    19/09/2023
12       William Riley  AI & Machine Learning      Beginner    20/09/2023

In [9]:
df['Course'] = df['Course'].str.capitalize()
df

                  Name                 Course   CourseLevel FormattedDate
0   Christy Cunningham                 Python      Beginner    10/09/2023
1       Douglas Tucker                 Python       MASTER     11/09/2023
2       Travis Walters                   Java  Intermediate    12/09/2023
3     Nathaniel Harris        Web development      Advanced    13/09/2023
5         Tonya Carter  Ai & machine learning      Beginner    14/09/2023
6           Erik Smith     Mobile development      Beginner    15/09/2023
7   Kristopher Johnson                 Python      Beginner    16/09/2023
9          Robert Buck                 Python       Master     17/09/2023
10     Joseph Mcdonald                   Java  Intermediate    18/09/2023
11       Jerome Abbott        Web development      Advanced    19/09/2023
12       William Riley  Ai & machine learning      Beginner    20/09/2023

In [10]:
df['CourseLevel'] = df['CourseLevel'].str.capitalize()
df

                  Name                 Course   CourseLevel FormattedDate
0   Christy Cunningham                 Python      Beginner    10/09/2023
1       Douglas Tucker                 Python       Master     11/09/2023
2       Travis Walters                   Java  Intermediate    12/09/2023
3     Nathaniel Harris        Web development      Advanced    13/09/2023
5         Tonya Carter  Ai & machine learning      Beginner    14/09/2023
6           Erik Smith     Mobile development      Beginner    15/09/2023
7   Kristopher Johnson                 Python      Beginner    16/09/2023
9          Robert Buck                 Python       Master     17/09/2023
10     Joseph Mcdonald                   Java  Intermediate    18/09/2023
11       Jerome Abbott        Web development      Advanced    19/09/2023
12       William Riley  Ai & machine learning      Beginner    20/09/2023

In [11]:
fonts_path = "/content/drive/MyDrive/fonts"

In [12]:
# reportlab library ---> pdfmetrics
# .ttf is an extension for fonts file

# TTFont() we will need 2 input
# 1st input --> font type we need register
# 2nd input --> where is the font

pdfmetrics.registerFont(TTFont('Lora-Bold', fonts_path + '/Lora-Bold.ttf'))
pdfmetrics.registerFont(TTFont('Lora-Regular', fonts_path + '/Lora-Regular.ttf'))

In [13]:
# Creating Certificate Logic Function --> create cert
# function need 4 input (name, course, course level, date)

# use this 11 times

def certificate_generator(name,courseName,courseLevel,date):
  pdf_file_name = "/content/drive/MyDrive/certificates/" + name + "-" + courseName + "-" + courseLevel + ".pdf"
  c = canvas.Canvas(pdf_file_name, pagesize= landscape(A4))
  c.drawImage("/content/drive/MyDrive/Image20260308185706.jpg", 0 ,0, width = A4[1], height= A4[0])
  # up till this point, we basically have an empty A4 landscape canvas --> drew it with the cert template.

  # Before populating the data (4 inputs --> name,courseName,courseLevel,date) into this certificate...
  # Let's calculate the center of the A4 lanscape page
  # because when we draw the (courseName, courselevel, date), we don't want to start from 0,0 --> top left corner
  # instead (in this context), it will be easier and faster to start from the middle of the page
  print('----------------------')
  # middle of the A4 page (width) --> middle because /2
  center_x = c._pagesize[0] / 2
  #crosscheck by printing
  print("Full width of the A4: ", c._pagesize[0]) # full width of the A4 canvas size
  print("Center of the A4 (x-axis): ", center_x) # center A4 canvas size (x-axis)
  print('-----')
  # middle of the A4 page (height) --> middle because /2
  center_y = c._pagesize[1] / 2
  #crosscheck by printing
  print("Full height of the A4: ", c._pagesize[1]) # full height of the A4 canvas size
  print("Center of the A4 (y-axis): ", center_y) # center A4 canvas size (y-axis)
  print('----------------------')
  c.save()

In [14]:
certificate_generator(df['Name'][1],df['Course'][1],df['CourseLevel'][1],df['FormattedDate'][1])
certificate_generator("Olivia", "Python", "Beginner", "29/03/04")

----------------------
Full width of the A4:  841.8897637795277
Center of the A4 (x-axis):  420.94488188976385
-----
Full height of the A4:  595.2755905511812
Center of the A4 (y-axis):  297.6377952755906
----------------------
----------------------
Full width of the A4:  841.8897637795277
Center of the A4 (x-axis):  420.94488188976385
-----
Full height of the A4:  595.2755905511812
Center of the A4 (y-axis):  297.6377952755906
----------------------

In [15]:
# Version 3

def certificate_generator(name,courseName,courseLevel,date):
  pdf_file_name = "/content/drive/MyDrive/certificates/" + name + "-" + courseName + "-" + courseLevel + ".pdf"
  c = canvas.Canvas(pdf_file_name, pagesize= landscape(A4))
  c.drawImage("/content/drive/MyDrive/Image20260308185706.jpg", 0 ,0, width = A4[1], height= A4[0])
  center_x = c._pagesize[0] / 2
  center_y = c._pagesize[1] / 2

  # now set font and draw text

  # .setFont() --> need 2 inputs
  # 1st input --> font type
  # 2nd input --> font size (in px)

  # .drawCentredString() --> 3 inputs
  # 1st input --> x axis
  # 2nd input --> y axis
  # 3rd input --> what we want to draw

  # 1. Name
  c.setFont("Lora-Bold", 30)
  c.drawCentredString(center_x, center_y - 46, name)

  # 2. CourseName & CourseLevel
  c.setFont("Lora-Bold", 28)
  c.drawCentredString(center_x,center_y - 105, courseName + "-" + courseLevel)

  # 3. Date
  c.setFont("Lora-Bold", 17)
  c.drawCentredString(center_x + 185, center_y - 160, date)

  # 4. Cert ID
  cert_id = "Cert ID: " + str(pd.Timestamp.now().timestamp()).replace(".","")
  c.setFont('Lora-Regular', 12)
  c.drawCentredString(center_x + 255, center_y - 230, cert_id.upper())

  c.save()

In [16]:
certificate_generator("Olivia", "Python", "Beginner", "08/03/26")

In [19]:
def certificate_generator(name,courseName,courseLevel,date):
  pdf_file_name = "/content/drive/MyDrive/certificates/" + name + "-" + courseName + "-" + courseLevel + ".pdf"
  c = canvas.Canvas(pdf_file_name, pagesize= landscape(A4))
  c.drawImage("/content/drive/MyDrive/Image20260308185706.jpg", 0 ,0, width = A4[1], height= A4[0])
  center_x = c._pagesize[0] / 2
  center_y = c._pagesize[1] / 2
  # 1. Name
  c.setFont('Lora-Bold',30)
  c.drawCentredString(center_x, center_y - 46 , name)
  # 2. CourseName
  c.setFont('Lora-Bold',28)
  c.drawCentredString(center_x, center_y - 105, courseName + " - " + courseLevel)
  # 3. Date
  c.setFont('Lora-Bold',17)
  c.drawCentredString(center_x + 190, center_y - 160, date)
  # 4. Cert ID
  cert_id = "Cert ID: " + str(int(pd.Timestamp.now().timestamp())) # Generating a UNIQUE id based on current time (timestamp)
  c.setFont('Lora-Regular', 12)
  c.drawCentredString(center_x + 266, center_y - 230 , cert_id.upper())
  c.save()

In [21]:
certificate_generator("hello","hi","hello","python")

In [24]:
for x in df:
  print(x)

Name
Course
CourseLevel
FormattedDate

In [34]:
# df.iterrows gives a loopable array-like
# 2 items, index and item

for index, x in df.iterrows():
  certificate_generator(x['Name'], x['Course'], x['CourseLevel'], x['FormattedDate'])
  print(index)

print(str(len(df))," certificates have been generated")

0
1
2
3
5
6
7
9
10
11
12
11  certificates have been generated